### PR TITLE
New pull request: 4K Gold able to be used for crafting

### PR DESCRIPTION
**Pull request by SlimeyDerp**
Added:

* 4K Gold able to be used as normal gold on a crafting bench

* .DS_Store added to .gitignore to avoid MacOS making "Ghost" files.

### CODE REVIEW

**Comment by WalshyDev** [comment]
You can push without reopening the entire PR.

**Comment by SlimeyDerp** [comment]
Probably, gotta learn how ;w;

**Comment by WalshyDev** [comment]
Literally just push your changes :p

**Comment by SlimeyDerp** [comment]
Will do next time

**Pull request merged**
