### PR TITLE
Tier 2 Electric Ore Grinder Speed and Energy is not at the proper value

### PR DESCRIPTION
**Pull request by NathanAdhitya**
Sorry, too much commits, my GitHub app is being buggy today.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Energy is supposed to be 15. This is Energy/Tick not Second...

**Comment by NathanAdhitya** [comment]
Oh, my bad. well, just change the speed then?

**Comment by TheBusyBiscuit** [comment]
Yep...

**Comment by NathanAdhitya** [comment]
Il push another pull request. :P

**Comment by TheBusyBiscuit** [comment]
Just merged your original one... :P

**Comment by NathanAdhitya** [comment]
Ah, there you go, thanks! <3 was actually quite dissapointing the time I upgraded to the tier 2... 
I was like, oh god did I ran out of energy...?

**Comment by NathanAdhitya** [comment]
OffTopic here, but wondering was how do one become a wiki staff? the email listed on there didn't gave any response, really.

**Pull request closed without merging**
