### PR TITLE
Updated Wiki Information

### PR DESCRIPTION
**Pull request by Solverbolt**
## Description

Just updating and filling out wiki information for all tools, machines and such, to better describe its assembly, its uses, among other things.   
## Changes

None, as without heavy amounts of autocorrect, and someone looking over my shoulder for grammar, no one would understand what i typed
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.

### CODE REVIEW

**Comment by WalshyDev** [comment]
You're pushing a stupidly old branch and I can't see any changes anyway. Plus, wiki changes go to the TheBusyBiscuit/Slimefun4-Wiki repo...

**Comment by Solverbolt** [comment]
sorry, could not figure out where to post, my bad

**Comment by TheBusyBiscuit** [comment]
Not really sure what the point of this troll pull request is...
Going to close it either way.

**Comment by Solverbolt** [comment]
wasnt a troll request. it was a genuine one.

**Pull request closed without merging**
