### PR TITLE
Experimental features

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

This is an aggregation of the following Pull Requests:
* #2220 "Rune of Employment" by @dniym 
* #2056  "Climbing Pick" by @LinoxGH 
* #2037  "Synthetic Shulkers" by @LinoxGH 

## Changes
In addition to these PRs there have been a few more changes, I added a dual-wielding ability to the Climbing Pick, added more Unit Tests and also done some refactoring.

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by LinoxGH** [comment]
What is this waiting tk be merged?

**Comment by TheBusyBiscuit** [comment]
> I originally called this nitwit rune however changed it to time of unemployment because If you set a villager to nitwit now they can never get a profession. Might be confusing for someone if they think the rune makes the villager unemployable.

Ahh okay, any other naming suggestion? I think Rune of Unemployment seems a bit off

> What is this waiting to be merged?
It's still "Unreviewed" which means it is pending for a review.

**Comment by dniym** [comment]
Maybe Merchants Rune?

**Comment by LinoxGH** [comment]
Rune of Resetting or Rune of De-Profess

**Pull request merged**
