### PR TITLE
Fix/fix 1212

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description

resolves 1212
## Changes
Changed priority so that this fires before itemuselistener
requires this pr merged too
https://github.com/TheBusyBiscuit/CS-CoreLib/pull/121
## Related Issues

#1212 

## Testability

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

**Comment by J3fftw1** [comment]
accidenlty removed the branch

**Comment by WalshyDev** [comment]
The word "idiot" comes to mind 😂😂😂

**Comment by J3fftw1** [comment]
i feel like my pr is getting abused

**Comment by TheBusyBiscuit** [comment]
yup

**Comment by WalshyDev** [comment]
To be fair, the idiot who deleted his branch deserves some abuse.

**Comment by J3fftw1** [comment]
> 
> 
> To be fair, the idiot who deleted his branch deserves some abuse.

WOW WOW WOW calm down malady

**Pull request closed without merging**
