### PR TITLE
Added an option to allow normal creative researching

### PR DESCRIPTION
**Pull request by John000708**

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
#122

**Comment by TheBusyBiscuit** [comment]
Okay no idea how the hell references work...

**Comment by flapjack1968** [comment]
Lol, it seems like the reference worked.  I could click through to the posts and it looks like you're made some progress on this already.  Do we just add the "allow-free-creative-research: true " line to the config or do we need to wait for the next version release?

**Comment by John000708** [comment]
You wait for a new release, or you compile it by yourself...

**Pull request merged**
