### PR TITLE
Added CS-CoreLib permission check for Slimefun Machines

### PR DESCRIPTION
**Pull request by Redemption198**
Added CS-CoreLib permission check for Slimefun Machines.
Updated some deprecated methods.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Ehhhm, why are there so many whitespace changes?

**Comment by Redemption198** [comment]
I used Eclipse Auto-Indentation so it tabbed everything to correct the indentation, I'll delete these tabs as soon as possible.

**Comment by Redemption198** [comment]
I was checking the code again, and I noticed that I didn't add spaces, I think these changes are related to the "extra" ifs I added that caused the entire code to shift a few lines, so Git counts that shift as a change, what shall I do?

**Comment by Redemption198** [comment]
Thank you so much :D

**Comment by KyleEstein** [comment]
This commit converted every LF in SlimefunSetup.java into a CRLF

**Pull request merged**
