### PR TITLE
fix cargo input/output slot with furnace

### PR DESCRIPTION
**Pull request by Dinnerwolph**
fix https://github.com/TheBusyBiscuit/Slimefun4/issues/114 with changement

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
This is not what I meant.
Cargo Nodes need to be placed on the side of a block, please do not change that.

**Comment by Dinnerwolph** [comment]
can be from the node inventory ?

**Comment by TheBusyBiscuit** [comment]
What?

**Comment by Dinnerwolph** [comment]
a button that selects the slot

**Comment by TheBusyBiscuit** [comment]
That would be cool, you could add an Advanced Input Node which can do that.

**Pull request closed without merging**
