### PR TITLE
Call BlockBreakEvent in ExplosivePickaxe and ExplosiveShovel

### PR DESCRIPTION
**Pull request by js6pak**
## Description
Made explosive tools compatible with other plugins listening to BlockBreakEvent

## Changes
Added BlockBreakEvent call in ExplosivePickaxe and ExplosiveShovel

## Testability

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

**Comment by WalshyDev** [comment]
Not sure that firing BlockBreakEvent is a good idea. Some plugins may do quite a few operations here and firing it 9/18/27 times is just ew.

**Comment by TheBusyBiscuit** [comment]
Not to mention that this will trigger a LOT of Anti-Cheat plugins out there and noone wants to add compatibility to all of those...

**Comment by WalshyDev** [comment]
If you want this then make a custom event

**Comment by js6pak** [comment]
But still no one wants to add custom event compatibility to every plugin using block break event, maybe make it optional in config or something?

**Comment by WalshyDev** [comment]
It will break in more plugins than it will help. I can't see a valid use case which couldn't just implement a custom event. 

Please explain your usage

**Comment by js6pak** [comment]
Custom block drops, block logger not supported by CSCoreLib

**Comment by WalshyDev** [comment]
Can do it with event priority and "block logger" isn't that helpful but again, priority solves it.

**Comment by TheBusyBiscuit** [comment]
CSCoreLib DOES actually support block loggers, just only LogBlock and CoreProtect, you can add an implementation for the plugin you are using yourself.
https://github.com/TheBusyBiscuit/CS-CoreLib2/tree/master/src/main/java/io/github/thebusybiscuit/cscorelib2/protection/loggers

**Comment by js6pak** [comment]
I know, that's why I said 

> block logger **not supported by CSCoreLib**

and if block logger is closed source then it's just easier to add block break event here that implementing it in cscorelib
But custom block drops are still most important for me

**Comment by WalshyDev** [comment]
Event Priority!

**Comment by js6pak** [comment]
Sorry but I don't know what you mean by event priority

**Pull request closed without merging**
