### PR TITLE
Fixed speed modifier not getting applied to Enhanced Furnaces

### PR DESCRIPTION
**Pull request by John000708**
Fixed an issue mentioned in #512  #453 #411

Happy new year.

### CODE REVIEW

**Comment by Poslovitch** [comment]
Happy New Year first.

But it looks like you didn't change anything : you just store the state in a variable instead of casting it each time.
Did you run some tests?

**Comment by John000708** [comment]
@Poslovitch I did and I was extremely amazed that it worked. You can go ahead and test it as well.

**Comment by Poslovitch** [comment]
Wow. Sounds kinda magical. Is the Christmas magic still in the air today? haha
Let me run some tests, and send you the results ;)

**Comment by Poslovitch** [comment]
Do you think it also fixes the duplication bug?

**Comment by John000708** [comment]
I don't think so. Have you been able to reproduce the duplication issue? I haven't messed with Slimefun for a very long time so I'm a bit rusty.

**Comment by Poslovitch** [comment]
No, I've never been able to reproduce the duplication issue.

Tried to test your fix, however due to #566, I can't give myself an Enhanced Furnace. I'll have to work on that thing too. So much bugs have popped from nowhere these times...

**Comment by Poslovitch** [comment]
By the way, here is a tiny code-optimization for the whole #tick() method : 

```java
@Override
public void tick(Block b, SlimefunItem item, Config data) {
	if (b.getState() instanceof Furnace) {
		Furnace furnace = (Furnace) b.getState();
		if (furnace.getCookTime() > 0) {
			furnace.setCookTime((short) (furnace.getCookTime() + getSpeed() * 10));
			furnace.update(true, false);
		}
	}
}
```

**Comment by John000708** [comment]
> No, I've never been able to reproduce the duplication issue.
> 
> Tried to test your fix, however due to #566, I can't give myself an Enhanced Furnace. I'll have to work on that thing too. So much bugs have popped from nowhere these times...

Hm.... That's weird. The items appear just fine for me. 

> By the way, here is a tiny code-optimization for the whole #tick() method :
> 
> @Override
> public void tick(Block b, SlimefunItem item, Config data) {
> 	if (b.getState() instanceof Furnace) {
> 		Furnace furnace = (Furnace) b.getState();
> 		if (furnace.getCookTime() > 0) {
> 			furnace.setCookTime((short) (furnace.getCookTime() + getSpeed() * 10));
> 			furnace.update(true, false);
> 		}
> 	}
> }

I purposely put the variable declaration inside the if-statement. No need to declare it every tick, even when the furnace isn't running.

**Comment by Poslovitch** [comment]
Then this?

```java
@Override
public void tick(Block b, SlimefunItem item, Config data) {
	if (b.getState() instanceof Furnace)
		if (((Furnace) b.getState()).getCookTime() > 0) {
			Furnace furnace = (Furnace) b.getState();
			furnace.setCookTime((short) (furnace.getCookTime() + getSpeed() * 10));
			furnace.update(true, false);
		}
	}
}
```

So basically the same code as yours, without the NPE catch.

**Comment by John000708** [comment]
Yeah I assume so. I don't see anything that could cause an NPE there.

**Comment by Poslovitch** [comment]
Okey, then can you push a commit with this change

**Comment by John000708** [comment]
Could somebody else also test this fix, just to be sure I'm not insane?

**Pull request merged**
