### PR TITLE
Switching to lambdas

### PR DESCRIPTION
**Pull request by Trigary**
Lambdas make the code a lot cleaner, especially in situations showcased in this video (while changes on top of lambadas should be applied to that piece of code): https://drive.google.com/file/d/1V3EVXq_aI5VnT-GdPIbyl3vY9DUSKhBb/view

### CODE REVIEW

**Comment by JanTuck** [comment]
+1

**Comment by TheBusyBiscuit** [comment]
Not a huge fan of using lambdas in every situation.
But I agree that this nested rabbit hole can use a clean up.

Maybe only use lambdas for this, if you cannot come up with an even better solution?

**Comment by Poslovitch** [comment]
I agree to this one. Lambdas are a great help in making the code cleaner and easier to read.

**Comment by TheBusyBiscuit** [comment]
@JanTuck This project started over 4 times, it started back in 2013.
Starting over is always a great oppurtunity, but then just create a new repository instead XD

**Comment by Trigary** [comment]
"Not a huge fan of using lambdas in every situation."
You seem to be against Java 8, by the looks of this and #600. May I ask what your problem is with lambas? Your project was shortened by 1500 lines of code by switching to them and became a lot more readable.

**Comment by JanTuck** [comment]
I’ve got my own projects to fiddle around with lol 😜

**Comment by TheBusyBiscuit** [comment]
@Trigary I don't have anything against Java 8.

I just don't really like using it all the time - personal preference of course.
For me interfaces and anonymous inners are saner to read.

And about #600 Mocking me for writing oh, so horrible code and then just changing a small aesthetic detail, just seemed unnecessary.
But I'm done feeding trolls (I don't mean you) for today.

**Comment by MisterFixx** [comment]
MY NAME JEFF

**Comment by Trigary** [comment]
And apparently I'm the /r/badcode guy: https://old.reddit.com/r/badcode/comments/7yhd28/how_to_not_lambda/
I hate you [mikroskeem](https://github.com/mikroskeem)!

**Pull request closed without merging**
