### PR TITLE
Updated for 1.13

### PR DESCRIPTION
**Pull request by PrzemoVi**
I rewrited everything to 1.13

Fixed particles,materials,setdata,etc.
Tested it on my mc server - endimc.pl (poland)

I will create Pull request for CS-CoreLib too. :)

### CODE REVIEW

**Comment by xH3LLRAIZ3Rx** [comment]
Well, you're clearly better at coding than me... :D

**Comment by PrzemoVi** [comment]
I don`t think so. I still cannot understand what interface and abstract class is :D

**Comment by VoidAngel** [comment]
Nice work. :D
I've been looking for bugs and I've found a few so far.

Ill report the first right now because its the probably easiest.
The WoolColor class messes up the rainbow terracotta, stained glass panes, and stained glass.
Those items use that method which turn it into wool xD

**Comment by PrzemoVi** [comment]
@VoidAngel - Fixed :)

**Comment by PrzemoVi** [comment]
@VoidAngel - Fixed :)

**Comment by VoidAngel** [comment]
There is a good chance I'm doing this wrong xD I'm probably missing some null checks... but what if you try something like this?
https://pastebin.com/h4Nuau8S
Then access it like so:
`menu.replaceExistingItem(42, new CustomItem(new ItemStack(ColoredBlock.WOOL.getColoredBlock(channel))......`
or
`b.setType(ColoredBlock.fromBlockType(b.getType()).getColoredBlock(meta));`

It could be more of a general tool for all of the colored blocks. Also its more condensed, and will stay condensed even if more blocks that follow this pattern are added in the future.

**Comment by PrzemoVi** [comment]
In 1.13 Every wool has other Type, you cannot use 42 or Material.WOOL

**Comment by VoidAngel** [comment]
I was using actual slimefun examples to show the usage xD I think you misunderstood.
Here is a very plain example of the usage:
`Material material = ColoredBlock.WOOL.getColoredBlock(1);`
This would return a material of type ORANGE_WOOL.
Another example:
`Material material = ColoredBlock.STAINED_GLASS_PANE.getColoredBlock(10);`
This would return a material of type PURPLE_STAINED_GLASS_PANE

**Comment by PrzemoVi** [comment]
Done. It was really good idea!

**Comment by VoidAngel** [comment]
awwh
:')

**Comment by PrzemoVi** [comment]
On my server this thread is now generating less cpu usage <3

**Comment by underestimate** [comment]
How to get a copy of the 1.13 version?

**Comment by VoidAngel** [comment]
@underestimate Normally you would have to compile it from PrzemoVi's Slimefun repository, along with PrzemoVi's CSCoreLib repository.

I can pass you the compiled jars if you want to help find bugs.

**Comment by underestimate** [comment]
Yes please If you don't mind :)

**Comment by VoidAngel** [comment]
https://www.dropbox.com/s/mae520xbw8iquwy/Slimefun1.13.zip?dl=0

**Comment by Meta-Win** [comment]
You can break the Ancient Pedestals during a ritual, get your items back and complete the ritual
https://i.imgur.com/KrKEKVB.png

**Comment by VoidAngel** [comment]
@Meta-Win 
Thanks for the heads up 👍 
I went ahead and checked out the misc thing. Without addons I believe there shouldnt be a second page right? So there must just be a ghost item in that category or something D: But no big deal I'm sure.

About the glass, I guess now that the different colored glass panes are completely different blocks, we have to use setType instead of setData 🤔 This sort of clears the directional properties of the panes. Anyone know a way to fix this? I dont really know anything about how bukkit handles the connecting glass, or what type of data that is.

**Comment by PrzemoVi** [comment]
Here: https://drive.google.com/drive/folders/13rSlLxNKxH_hRLXsOVNwZtqzNO3bp8DS?usp=sharing

**Comment by PrzemoVi** [comment]
@VoidAngel I think, this is calculated client-side

**Comment by PrzemoVi** [comment]
So, I fixed it :smile: 
Maybe it is not the best way, but it is working!

**Comment by PrzemoVi** [comment]
"Miscellaneous" category is hardcoded to two pages, but there is no item on second page.
I can remove second page if You wand

**Comment by xH3LLRAIZ3Rx** [comment]
@PrzemoVi You need to edit SlimefunStartup to add v1_13 to the list of viable versions

**Comment by creator3** [comment]
You accidentally copied the src directory into a new Slimefun directory. The diff is insane. xD

**Comment by PrzemoVi** [comment]
Ready jar files on my google drive:
https://drive.google.com/open?id=13rSlLxNKxH_hRLXsOVNwZtqzNO3bp8DS

**Comment by VoidAngel** [comment]
creator3 is right, this PR has a low chance of being accepted anyways, but if the package is messed up there is no way it can be accepted.
@PrzemoVi Are you able to fix the packaging?

**Comment by PrzemoVi** [comment]
@VoidAngel What is wrong with this packaging?

**Comment by xH3LLRAIZ3Rx** [comment]
@PrzemoVi the updated source of yours is in a Slimefun folder rather than the main src folder

**Comment by VoidAngel** [comment]
Your code should be in Slimefun4/src/... but yours is in Slimefun4/Slimefun/src/...
So basically you have 2 src folders in your setup. The way normal slimefun setup is supposed to have 1 src.

**Comment by PrzemoVi** [comment]
Wtf...
How can i change it?
( I`m using java eclipse )

**Comment by Onlyausername** [comment]
Maybe you can delete the "Slimefun4-master\src" folder, and move the "Slimefun4-master\Slimefun\src" to the main folder("Slimefun4-master\src")
And remove the "Slimefun4-master\Slimefun\src" from the Java Build Path on Project Properties

**Comment by WaverlyCole** [comment]
Life saver, thanks man! You just made a server very happy.

**Comment by PrzemoVi** [comment]
I deleted my old repository and make a new one.
I will create new PR.

**Pull request closed without merging**
