### PR TITLE
Added recipes

### PR DESCRIPTION
**Pull request by BurningBrimstone**
## Description

Changes are for the electric press.
Added recipes for iron and gold nuggets into their respective ingots. I also added a recipe for quartz into quartz blocks. 

https://discordapp.com/channels/565557184348422174/627048923122499584/652563773793763343

## Changes

Same as above. 

## Testability

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

**Comment by WalshyDev** [comment]
Build is failing, the material isn't called `NETHER_QUARTZ`, please look at the Javadocs and correct this.

**Comment by BurningBrimstone** [comment]
> 
> 
> Build is failing, the material isn't called `NETHER_QUARTZ`, please look at the Javadocs and correct this.

My apologies, changed to "QUARTZ". I seem to recall the namespace ID being NETHER_QUARTZ but the wikia denies that.

**Comment by TheBusyBiscuit** [comment]
I think that all other block recipes should be added too if we already have Quartz blocks.

**Comment by BurningBrimstone** [comment]
I would be inclined to agree. But the addition of quartz blocks serves to assist in automation of solar panels and silicon, a major electric resource.

I was discussing with panda about adding the resource blocks and they made a valid point that adding to much more functionality to the electric press would qualify it to be a small addon.

Nonetheless, if you want me to add them, I will.

**Comment by TheBusyBiscuit** [comment]
Normally I am always for putting stuff rather in an addon.
But this is a very specfic use-case that fits to this machine.

And since we already have quartz blocks, it'd be weird to make the other require an addon...
There will probably come requests to add them anyway at some point.

**Pull request merged**
