### PR TITLE
Compatibility with 1.12

### PR DESCRIPTION
**Pull request by VanishTime**
Repair enhanced furnace speed is the same as the original.
(Sorry of my bad english...)

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
You literally haven't changed anything!?

**Comment by VanishTime** [comment]
Sorry...but the previous way didn't work on PaperSpigot...

**Comment by VanishTime** [comment]
Maybe it's because of 1.12 update, but this will solve the problem.

**Comment by andris155** [comment]
kepkivagas

**Comment by VanishTime** [comment]
Looks...I forget somethings..?

**Comment by andris155** [comment]
Thanks!

**Comment by andris155** [comment]
I using this pr and Slimefun furnace bugged.. https://www.youtube.com/watch?v=vveIdyuV4uA

**Comment by VanishTime** [comment]
Sorry...this bug isn't made by me.  #411 
But can you tell me your environment? I didn't happen this.

**Comment by mrcoffee1026** [comment]
The oven has had that bug since 4.10. (vid linked by andris155).  If your pull request repairs the speed issue that has been present since 4.9... it doesn't fix this particular issue is what he's saying.  It doesn't happen ALL the time.  The oven occasionally drops loads of fuel and items it's to be smelting non stop... independently of what was originally put into the oven.  Too bad this pull request wasn't dealing with that issue, that makes me sad.

**Comment by akashaggarwal7** [comment]
@mrcoffee1026 Is this why the EnhancedFurnace has been removed from 1.12 menu? At least it doesn't show up for me in the latest build..

**Comment by mrcoffee1026** [comment]
@akashaggarwal7 no this has nothing to do with that?  Since they're still showing in the menu for me I think it must be for some other reason they're not appearing.  I've not attempted *this* pull request, I rolled back to release 1.9 since 1.10 broke cargo.  Dev stated 1.11 fixes cargo again, but since there still isn't a 1.11 available to download... anyway, 1.9 does not have the bizarre item/fuel duplication/drop issue that 1.10 has either, however both 1.9 and 1.10 have the speed issue.  Both of these releases (1.9 and 1.10) appear to obey the "efficiency", however, using fuel more effectively than vanilla ovens even though they cook as slow as vanilla ovens.  If This pull fixes the speed, it seems 1.10 needs an additional revert to undo whatever else was done to the oven, but having it mysteriously vanish wasn't one (this may have been covered by the other bug report with the lava bucket earlier).

**Comment by akashaggarwal7** [comment]
@mrcoffee1026 I figured it, its because the contents of the config file doesn't get copied. So the config file only has comments and no configuration.

**Comment by Poslovitch** [comment]
This PR doesn't correspond to how the code actually works : it adds a "placeable" variable to SlimefunItem, which is technically already done by the interface NotPlaceable, and is an option that shouldn't be given to the users of the plugin.

**Comment by TheBusyBiscuit** [comment]
Not mergeable due to file conflicts.
Not properly done as @Poslovitch stated.

**Pull request closed without merging**
