### PR TITLE
WorldEdit 7.0 support, Ancient Altar fix.

### PR DESCRIPTION
**Pull request by PrzemoVi**
WorldEdit 7.0 fix
I tested it, and it works perfectly on latest spigot & worldedit :)
But this will broke support to older worldedit versions.

### CODE REVIEW

**Comment by ericbarbwire** [comment]
This is an awesome addition, can't wait to see it added to the dev builds on the repo server!

**Comment by PrzemoVi** [comment]
My modified .jars (both cscorelib and slimefun):
https://drive.google.com/open?id=16Ru4UAN3QEr1uTJ3OETRUN5lJUjrw0J5

Fixed worldedit 7 (my request https://github.com/TheBusyBiscuit/Slimefun4/pull/814)
Fixed enchanted furnaces and lumber axe duplication glitch (https://github.com/TheBusyBiscuit/Slimefun4/pull/810)
Fixed auto. crafting. table, electric furnace and charging bench (my request https://github.com/TheBusyBiscuit/CS-CoreLib/pull/64)
Fixed Ancient Altar itemstack fixing ;) (my request https://github.com/TheBusyBiscuit/Slimefun4/pull/814)

Warn: This will broke support with worldedit older than 7.0!!!

**Comment by MothGirlMusic** [comment]
if this needs votes or a vouch from someone who's tested this on their server for someone to even look it over, then i totally vouch for this. its stable, it actuaally fixes those issues, and i'm using it on my production server live with players now. zero issues. i haven't tested the ancient altar fix yet, but i have tested everything else.

**Comment by TheBusyBiscuit** [comment]
Just a heads up, these PRs did not go unnoticed.
Right now I am just very ill and cannot review anything.

In the mean time, please do not advertise/distribute unofficial builds so vigoriously, rather wait for the Pull request to be accepted, then there will be an official build uploaded automatically.

**Pull request merged**
