### PR TITLE
Check if the chunk is loaded instead of relying on exceptions

### LINKED ISSUE #509: SlimeFun spitting errors in Console
## Description
Describe your Issue AS DETAILED AS POSSIBLE.
Slimefun Spitting Errors in Console
## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/NG0GMnXx
## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
-
## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
PaperSpigot 1.12.2 v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.10
Barrels v1.11
SlimeXpansion v1.1.9

### PR DESCRIPTION
**Pull request by meiamsome**
(Maybe) Fixes #509

It would be ideal for @itslukemango or @andris155 or anyone running Paper to check if this fixes it. It does not throw any exceptions on my Spigot testing, so it shouldn't cause issues on Paper.

### CODE REVIEW

**Comment by lukemango** [comment]
We changed to Spigot rather than Paper, so I can't test it right now.

**Comment by meiamsome** [comment]
@lukemango Thanks for getting back to me regarding this.

In other news, this fix doesn't work (`.getChunk()` loads the chunk these days) - I'll push an update in a bit.

**Comment by meiamsome** [comment]
The second commit includes an attempted fix for #487 - by using Location instead of Block the ticker task won't cause an Async Chunk Load. this adds some Deprecations to the API, but I haven't resolved these in the other classes yet.

**Comment by TheBusyBiscuit** [comment]
Migrating everything to Locations is great. But I wouldnt advise renaming the method to getLocationInfo(), addLocationInfo etc...
just keep the name, and deprecate all methods that use a Block argument rather than a Location one.

**Comment by meiamsome** [comment]
I originally kept the names of them with Block in, and then I got to this method:
```java
public static Set<Block> getTickingBlocks(Chunk chunk)
```
Which conflicts with the form of 
```java
public static Set<Location> getTickingBlocks(Chunk chunk)
```
And so I had to change the name of that one to Location and therefore I decided I should rename the others for consistency.

**Comment by TheBusyBiscuit** [comment]
@meiamsome I see, okay.

**Pull request merged**
