### PR TITLE
Adding Storm Staff.

### PR DESCRIPTION
**Pull request by LinoxGH**
- Adding a new staff called "Storm Staff".
- Adding a new research called "Storm Staff".
- Adding a new recipe for Storm staff containing:
  - 1 Air Rune and 1 Water Rune.
  - 1 Wind Staff and 1 Water Staff.
  - 1 Ender Lump 3.
- Storm Staff consumes as much hunger as Wind Staff.
- Storm Staff lets the player to create lightnings where the player looks at in a maximum range of 50 blocks.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Uggh, I think this Item is way too overpowered to just throw onto hundreds of servers all of the sudden.

**Comment by LinoxGH** [comment]
perhaps we can make it only have 5 uses?

**Comment by TheBusyBiscuit** [comment]
That, maybe a bit more hunger cost, higher research cost and a different Recipe with an Ancient Altar to set the bar higher?

You could also change the texture from a Stick to a Blaze Rod.

**Comment by LinoxGH** [comment]
Blaze rod is kind of fiery. This rod is a combination of air and water so I think Stick would fit better. Gonna do the other changes though.

**Comment by TheBusyBiscuit** [comment]
Alrighty!

**Comment by LinoxGH** [comment]
Wait for some reason git didn't merge my local SlimefunSetup.java with my GitHub repo.

**Comment by TheBusyBiscuit** [comment]
I saw, you may have just selected the wrong line endings though.

**Comment by LinoxGH** [comment]
I am VERY new to Git. I'll fix this asap.

**Comment by LinoxGH** [comment]
Going to create a new PR with more reasonable commits.

**Pull request closed without merging**
