### PR TITLE
Minor fix and enhancement to tab completion

### PR DESCRIPTION
**Pull request by akashaggarwal7**
Fixed a typo and added the ability to complete words on tab completion smartly.

### CODE REVIEW

**Comment by John000708** [comment]
This might cause problems with the Colored Enderchests, since there's thousands of them

**Comment by akashaggarwal7** [comment]
@John000708 Item name(s)?

**Comment by John000708** [comment]
@akashaggarwal7 yeah, if I can recall correctly, it adds 8192 new items which means 8192 new ids your loop has to go through.

**Comment by akashaggarwal7** [comment]
@John000708 I'm unaware of them being a part of slimefun. Is it a planned released or another plugin?

**Comment by John000708** [comment]
Here you go: https://dev.bukkit.org/projects/colored-ender-chests

**Comment by akashaggarwal7** [comment]
@John000708 Well that sucks.. I could remove it for the give and research command for now and perhaps we can use a better algorithm for search in the future(I can't think of one right now)?

**Pull request merged**
