### PR TITLE
Synthetic Shulker shells

### PR DESCRIPTION
**Pull request by LinoxGH**
## Description

Added a new recipe for shulker shells in SF.

## Changes

Added a new recipe for ancient altar.
From approved suggestion #180

## Related Issues

N/A

## Checklist

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [X] I followed the existing code standards and didn't mess up the formatting.
- [X] I did my best to add documentation to any public classes or methods I added.
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Not really sure what to think of this one.
I was okay with recipes for Totems or Elytras. But Shulker Shells? They're not really that hard to come by, are they?

**Comment by LinoxGH** [comment]
They are in big servers. In them the end is pillaged/looted for thousands of blocks away from the portal. And whrn a city is looted no more new shulkers spawn.

**Comment by EnderBro123** [comment]
> They are in big servers. In them the end is pillaged/looted for thousands of blocks away from the portal. And whrn a city is looted no more new shulkers spawn.

(Never comment on these usually)

Or, what about making it so endermites after a while burrow into purpur blocks and turn into shulkers.

**Comment by LinoxGH** [comment]
> > They are in big servers. In them the end is pillaged/looted for thousands of blocks away from the portal. And whrn a city is looted no more new shulkers spawn.
> 
> (Never comment on these usually)
> 
> Or, what about making it so endermites after a while burrow into purpur blocks and turn into shulkers.

Looked into this a little and from what I've found I need to do Packet or NMS stuff if I want this to happen in Spigot(this can be done in Paper though)

**Comment by TheBusyBiscuit** [comment]
Well, that was an unfortunate accident :/

**Comment by LinoxGH** [comment]
> Well, that was an unfortunate accident :/

Maybe merge this for no more accidents? :3

**Comment by TheBusyBiscuit** [comment]
:LUL: We will see. This PR is definitely up next now that we got the more important ones merged like the Metrics one or the whole other load of PRs you have created.

I will still need to review this Shulker Shell PR though in terms of balancing, so I cant guarantee that it will still make it before or after the next "stable" version.

**Pull request merged**
