### PR TITLE
Altar Item fixes

### PR DESCRIPTION
**Pull request by XjCyan1de**
Fixed: Item puckup after server restart
Fixed: Item despawn
Fixed: Item texture when using Optifine CIT texture in Resource Pack

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Do not remove the no_pickup metadata part. Your changes are fine but this needs to stay in...

**Comment by XjCyan1de** [comment]
Metadata only saves if server on, after restart its clear. If use vanilla ScoreBoard tag its works good. I just tested it

**Comment by TheBusyBiscuit** [comment]
... I never said metadata is better -_-

As I said, you can add your code, but this metadata tag is widely used by multiple Addons and needs to stay...

**Comment by XjCyan1de** [comment]
So its also can replace `(n.hasMetadata("no_pickup"))` (24 line) in ClearLaggIntegration.oNEntityRemove to `n.getScoreboardTags().contains("AltarItem")`

**Comment by XjCyan1de** [comment]
Okay i will change it without remove

**Comment by TheBusyBiscuit** [comment]
Its also 1.11 only. And therefore removes Slimefuns cross compatibility. Not gonna accept this now.

**Comment by XjCyan1de** [comment]
Scoreboard tag added in 1.9 and it worked on it too

I just suggested how you can do better. But if you think that it is better to leave then I will not insist. Have a good day!

**Comment by TheBusyBiscuit** [comment]
I had to leave for work, so I only took a glimpse at CraftBukkit 1.10 and it didnt seem to contain that method. If you can show me that the method exists in 1.9 I will not stand in your way.

**Pull request closed without merging**
