### PR TITLE
Operational safety.

### PR DESCRIPTION
**Pull request by alekso56**
Fix errors :v:

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
You dont fix an Error by simply surrounding it with an empty try/catch ...

**Comment by alekso56** [comment]
You could put an System.out.println there if you so wished, the field for itemslots still changed in 1.10.2
it is now  "bB"

**Comment by TheBusyBiscuit** [comment]
Then change ONLY that, but adding empty tra/catch is the EXACT OPPOSITE of bug fixing...

**Comment by alekso56** [comment]
So eh, this?
https://github.com/alekso56/Slimefun4/commit/97b58842a514e6979ef9ce46401770ee6f8334f2

**Comment by TheBusyBiscuit** [comment]
(facepalm) No...

**Comment by alekso56** [comment]
Afaik my try/catch blocks are not empty tho? .-.

**Comment by TheBusyBiscuit** [comment]
-_- Still unncessary as they surpress the actual stacktrace...

**Comment by alekso56** [comment]
I don't think the user should be exposed to a stacktrace here tho.

**Comment by TheBusyBiscuit** [comment]
You are really making me worry about the future of programming...
"If we pretend there is no bug, there is no bug" or what?
Seriously? If that comment you just posted was honest, then you may want to rethink whether coding is something for you...

**Pull request closed without merging**
