### PR TITLE
Updated to 1.13

### PR DESCRIPTION
**Pull request by xH3LLRAIZ3Rx**
I went ahead and updated Silmefun to 1.13.

Do note I did not fix any warnings, I mainly just replaced all materials with the updated versions. I also added TODO's to the block.setData for fixing since setData() is removed in 1.13.

### CODE REVIEW

**Comment by Meta-Win** [comment]
I think it's necessary to fix deprecations and update CSCoreLib too

**Comment by xH3LLRAIZ3Rx** [comment]
I did update CS-CoreLib, but im struggling on a alternative to setData() and changing material data of wool and logs

**Comment by thefallenone12** [comment]
is there a download for both of these we can download yet?

**Comment by xH3LLRAIZ3Rx** [comment]
At its current form no because there's bugs that need fixing

**Comment by thefallenone12** [comment]
oh alright thats understandable. thank you

**Pull request closed without merging**
