### PR TITLE
Fix Pickaxe of Vein Mining Dupe

### PR DESCRIPTION
**Pull request by DeathlyPanda**
Fixed pickaxe to prevent duplication of ores.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
It would be wiser to use
´´drop.getType().isBlock()´´ instead.

**Comment by DeathlyPanda** [comment]
That change i did to vein pick is your own code from explosive pick and it works. Tested

**Comment by TheBusyBiscuit** [comment]
My point stands.

**Comment by DeathlyPanda** [comment]
Changed if you want to check it out

**Comment by TheBusyBiscuit** [comment]
Instead of the IRON/GOLD check not the ore check...
The point is to check if the block is an ore and the drop is a block...

**Comment by DeathlyPanda** [comment]
if (SlimefunManager.isItemSimiliar(e.getPlayer().getItemInHand(), SlimefunItems.PICKAXE_OF_VEIN_MINING, true) && e.getBlock().getType().toString().endsWith("_ORE")) {

ooh look it already checks if it is an Ore.

**Pull request merged**
