### PR TITLE
Mob drop chance

### PR DESCRIPTION
**Pull request by dniym**
Adds an optional % chance for a drop to happen, currently only checked when a mob would drop the item.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Nice idea, but no Item uses it? Also unsure whether it should go into SlimefunItem.class or a subclass of it.

**Comment by dniym** [comment]
Yeah, nothing uses it just yet, but I’ve got plans for it :D, if the chance is set and it’s a mob drop it’ll only drop on the chance otherwise it assumes 100% to not interfere with existing drops

**Comment by TheBusyBiscuit** [comment]
I know, I still think it could be moved to a subclass though.
And sorry but I am going to hold back on merging this for now until it has a real use.

**Comment by LinoxGH** [comment]
If this was added this could be implemented to Basic Circuit Boards, as I think 100% drop chance is absurd.

**Comment by TheBusyBiscuit** [comment]
I still think it shouldn't be part of the SlimefunItem base class, as 99% of items don't use it.
Best would be an Interface, then you could do an instanceof check and get the chance from there.

**Pull request closed without merging**
