### PR TITLE
Fixed teleporters not functioning if the teleport event is cancelled

### PR DESCRIPTION
**Pull request by OmerBenGera**
## Description

Fixed an issue when teleporters stopped working when the event is cancelled.

## Changes

I changed it so the user will be removed from the teleportedUsers even if the event is cancelled.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Please follow the Pull Request template and use the checklist provided...

**Comment by OmerBenGera** [comment]
> 
> 
> Please follow the Pull Request template and use the checklist provided...

not gonna bother tbh, the change is so small and you can apply it yourself if you wish.
I am tired of customers contacting me after you're blaming the issues on my plugins, instead of just fixing your plugin.

**Comment by TheBusyBiscuit** [comment]
I told them to make a bug report on Slimefun's issue tracker but also inform you about this behaviour.

No idea where your aggresive behaviour is coming from but our templates exist for a reason.

**Comment by Skizzles** [comment]
I have no issue submitting the Bug report, but overall we should be able to all sort through these issues and get both plugins working together.

**Comment by TheBusyBiscuit** [comment]
> I have no issue submitting the Bug report, but overall we should be able to all sort through these issues and get both plugins working together.

I agree. I mean there isn't need to submit any bug report now if there is already a PR for it. But I would still wish people would respect the workflow and formats of other projects,

**Comment by OmerBenGera** [comment]
> 
> 
> I told them to make a bug report on Slimefun's issue tracker but also inform you about this behaviour.
> 
> No idea where your aggresive behaviour is coming from but our templates exist for a reason.

My aggressive comes from a point that you're blaming my plugins on every bug that is reported, instead of you taking a look at your code for more than a second and fix it.
You can't blame others on issues on your end. You literally told him that instead of me canceling the event (The event is cancellable, yeah?), I just need to teleport to another location. That's just ridiculous.
Furthermore, your template is so long for a small fix, which you can clearly see what was changed and how it fixes the issue, so again - no, I am not gonna fill it. I fixed the bug for you, in your plugin, because you can't do that yourself. Now it's your decision whether or not to accept it

**Comment by Skizzles** [comment]
> > I have no issue submitting the Bug report, but overall we should be able to all sort through these issues and get both plugins working together.
> 
> I agree. I mean there isn't need to submit any bug report now if there is already a PR for it. But I would still wish people would respect the workflow and formats of other projects,

With as much respect as I can show, some of the formats for slimefun take a lot of time to fill out. While I get its for gathering as much information as possible sometimes we do not have time to fully fill them out.

Specifically I run into this issue often and end up sending an admin instead of myself because the huge forms....

From a neutral stand point if there was less to fill out for those who took the time to look into the bug, provide screenshots, and more then it would be great.

Usually I go to Omer first just because its this:
Please enter as much details as you can to your ticket. Make sure you include the followings if necessary:
- Plugin Version
- Server Version
- Errors (Pastebin or ghostbin!)
- Ways to create the issue

Vs a giant document.

Again from my neutral standpoint.

**Comment by TheBusyBiscuit** [comment]
I will accept this pull request obviously since it fixes a bug that needed to be adressed.
But I can only hope that you will put your aggresions aside and be more respectful to others in the future.

> My aggressive comes from a point that you're blaming my plugins on every bug that is reported, instead of you taking a look at your code for more than a second and fix it.
You can't blame others on issues on your end. You literally told him that instead of me canceling the event (The event is cancellable, yeah?), I just need to teleport to another location. That's just ridiculous.

I told him to make a bug report on Slimefun's issue tracker, like him and me just said again. But I also mentioned that the behaviour seems to deviate from the intended API usage since the Player is teleported, just somewhere else, yet the event is cancelled entirely. I never once said that this wouldn't be a Slimefun-related issue, in fact I said the exact opposite.

> Furthermore, your template is so long for a small fix, which you can clearly see what was changed and how it fixes the issue, so again - no, I am not gonna fill it. I fixed the bug for you, in your plugin, because you can't do that yourself. Now it's your decision whether or not to accept it

I realize that I will probably not be able to change your attitude, so I can really only hope that you will learn from this and improve for the future.

Anyway, thanks for the contribution nonetheless.

**Review by TheBusyBiscuit — APPROVED** [review]

**Comment by OmerBenGera** [comment]
> 
> 
> I will accept this pull request obviously since it fixes a bug that needed to be adressed.
> But I can only hope that you will put your aggresions aside and be more respectful to others in the future.
> 
> > My aggressive comes from a point that you're blaming my plugins on every bug that is reported, instead of you taking a look at your code for more than a second and fix it.
> > You can't blame others on issues on your end. You literally told him that instead of me canceling the event (The event is cancellable, yeah?), I just need to teleport to another location. That's just ridiculous.
> 
> I told him to make a bug report on Slimefun's issue tracker, like him and me just said again. But I also mentioned that the behaviour seems to deviate from the intended API usage since the Player is teleported, just somewhere else, yet the event is cancelled entirely. I never once said that this wouldn't be a Slimefun-related issue, in fact I said the exact opposite.
> 
> > Furthermore, your template is so long for a small fix, which you can clearly see what was changed and how it fixes the issue, so again - no, I am not gonna fill it. I fixed the bug for you, in your plugin, because you can't do that yourself. Now it's your decision whether or not to accept it
> 
> I realize that I will probably not be able to change your attitude, so I can really only hope that you will learn from this and improve for the future.
> 
> Anyway, thanks for the contribution nonetheless.

The difference between us is that I care about bugs being fixed. I am not blaming others, but actually open my IDE and do something in order to fix them. You on the other hand first love to say others need to fix it, or others need to change their code so it will work with yours. Only after arguing with you that you need to fix it, you'll maybe start caring. Maybe I haven't been respectful towards you, but that's because you're telling *customers* that the issues are on *my end*, while clearly it's your fault. And not only that, here you're just lying! Here's the [proof](https://screenshots.skizzles.me/JIWA4/dUgocePO84.png) of you blaming my plugin and telling the customer to contact me because I need to teleport the player instead of canceling the event.
I agree that you at the end told the customer to make a bug report, but it was after you argued with him and told him to contact me. Why can't you just listen to them in the first place and ask them to make a bug report, instead of arguing and blaming others? I think that's a bit worse than not being respectful towards other developers after I do the job for them, and even when I do it they have complains about stupid templates that add literally nothing useful to the PR. Maybe in other cases they do, here they don't. Don't be a robot.

**Comment by TheBusyBiscuit** [comment]
I don't feel like there is much for me to add. I didn't blame you or others. And if you felt offended in any way, sorry for that.

I don't feel offended by your accusations but I would still like to point out that I am not as "lazy" as you characterize me:
https://github.com/TheBusyBiscuit/Slimefun4/graphs/contributors

Slimefun is Open-Source and very much lives only due to people actively reporting bugs or submitting new content/fixes.
And we very much encourage both bug reports and pull requests over here, here is a link to all recently closed issues, most of which were resolved by one of the project maintainers or through a pull request.
https://github.com/TheBusyBiscuit/Slimefun4/issues?q=is%3Aissue+is%3Aclosed

If that one screenshot is all you were sent, I can possibly understand your frustration but there is still no need to be this hostile.
Here is just one more screenshot to illustrate a bigger picture of the entire conversation.
0ddebae24059a9a5fae263bfa7563f14

Also just one little correction: Noone here is *"my customer"*, it's freely available software, so that term would be wrong, you could say "users" in that case. Not to mention that I am not **THE** developer of this plugin, over 155 people (now including you) have contributed to this project. I am merely the person who initially started it back in 2013. So if anything, one would be "our user" and not "my customer".

I realize that a lot of information gets lost on the way when there is a middle man involved but I hope I made it clear for you that I intend no hostility, that I am not "blaming you" or anyone for that matter and that I very much encourage bug reports and contributions. I agree that I may be a bit too strict on templates at times, but these templates have proven themselves over many years. Was it absolutely necessary for you to include that checklist? No of course not, but checking off whether or not you have tested your changes is a layer of transparency that we like to encourage in our contributors. After all, I am still thankful for the fix and hope that we can put *whatever this is* aside.

Anyway, I don't mean to drag this conversation out any longer, have a good day!

**Pull request merged**
